version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: refugioos-burn-after-reading_app_1
      APP_PORT: "80"

  app:
    image: ghcr.io/refugioos/burn-after-reading:0.1.6-refugioos.1
    restart: on-failure
    environment:
      PORT: "80"
      BAR_PASSWORD: "refugioos"
    volumes:
      - ${APP_DATA_DIR}/data:/data
